### ISSUE TITLE
Fails to subscribe properly on version 6.3.2 but will work with version 6.3.1

### ISSUE THREAD

**Issue by tjpeel** [MassTransit/MassTransit-Platform#1]
I have implemented a simple container that makes use of the platform lib. I was using version 6.3.1 and all was good, it connected to RabbitMQ and the consumer I was using declared all its exchanges and bindings etc. 

I update to MassTransit 6.3.2 and the container gets as far as connecting but then does no more. So none of the consumer behaviour is initialised.

Is this a known issue?

**Comment by phatboyg** [comment]
The was a change in the startup interface for 6.3.2, which requires a  ever version of the platform abstractions assembly.

**Comment by tjpeel** [comment]
But I have updated to the latest platform abstractions lib too and there are no changes to the startup interface?? Hence why I was confused.

If you're able to point to any code that might be helpful, thanks.

My setup is nothing big, just a simple consumer connecting to RabbitMQ all running from latest version of platform abstractions lib.
